// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBND-KrFaQ5q3eFsZhr8K5QJjc-HzlJ-i0',
    appId: '1:697476804309:web:447624582b18545520fc5c',
    messagingSenderId: '697476804309',
    projectId: 'com-lawadvisor-lawyer',
    authDomain: 'com-lawadvisor-lawyer.firebaseapp.com',
    storageBucket: 'com-lawadvisor-lawyer.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp5mtEkEwkZ9ezkbJL0tMzI9kW9MTafos',
    appId: '1:697476804309:android:5d58e32bd061249920fc5c',
    messagingSenderId: '697476804309',
    projectId: 'com-lawadvisor-lawyer',
    storageBucket: 'com-lawadvisor-lawyer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDh4gj5d7NxJD37IThbIelB0kWLbstNNA',
    appId: '1:697476804309:ios:2b670a9fe680a9fe20fc5c',
    messagingSenderId: '697476804309',
    projectId: 'com-lawadvisor-lawyer',
    storageBucket: 'com-lawadvisor-lawyer.firebasestorage.app',
    iosBundleId: 'com.lawadvisor.lawyer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDh4gj5d7NxJD37IThbIelB0kWLbstNNA',
    appId: '1:697476804309:ios:7d3a3e34c5037a9d20fc5c',
    messagingSenderId: '697476804309',
    projectId: 'com-lawadvisor-lawyer',
    storageBucket: 'com-lawadvisor-lawyer.firebasestorage.app',
    iosBundleId: 'com.example.lawyerConsultantForLawyers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBND-KrFaQ5q3eFsZhr8K5QJjc-HzlJ-i0',
    appId: '1:697476804309:web:6f0f87f0a1299d5220fc5c',
    messagingSenderId: '697476804309',
    projectId: 'com-lawadvisor-lawyer',
    authDomain: 'com-lawadvisor-lawyer.firebaseapp.com',
    storageBucket: 'com-lawadvisor-lawyer.firebasestorage.app',
  );
}
